import { Control } from "./Control";
import "./globals.css";
import Link from "next/link";

export const metadata = {
    title: "Web tutorials",
    description: "Generated by gyojinnk",
};

export default async function RootLayout({ children }) {
    const res = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", {
        next: { revalidate: 0 },
    });
    const topics = await res.json();

    return (
        <html>
            <body>
                <h1>
                    <Link href="/">WEB</Link>
                </h1>
                <ol>
                    {topics.map((item) => {
                        return (
                            <li key={item.id}>
                                <Link href={`/read/${item.id}`}>
                                    {item.title}
                                </Link>
                            </li>
                        );
                    })}
                </ol>
                {children}
                <Control />
            </body>
        </html>
    );
}
